site_name: TIPS documentation
nav:
  - Home: index.md
  - Workflow: workflow.md
  - TIPS CLI: cli.md
  - Extending TIPS: extend.md
plugins:
  - mermaid2
theme:
  name: material
markdown_extensions:
  - admonition
