site_name: The Interatomic Potential Suite
repo_url: https://github.com/teoroo-cmc/tips
repo_name: Teoroo-CMC/TIPS
nav:
  - Home: index.md
  - Get started:
      - Installation: start/install.md
      - Your first workflow: start/first_workflow.md
      - Configure your run: start/configure.md
      - License: start/license.md
      - Resources:
          - Getting help: start/help.md
          - Alternatives: start/alternatives.md
          - References: start/references.md
  - Workflow:
      - Overview: recipe/overview.md
      - Recipes:
          - Benchmarking: recipe/benchmark.md
          - Active learning: recipe/active.md
      - Modules:
          - ASE: module/ase.md
          - CP2K: module/cp2k.md
          - LAMMPS: module/lammps.md
          - PiNN: module/pinn.md
          - Utils: module/utils.md
  - Library:
      - Overview: library.md
      - File formats: formats.md
      - CLI Commands:
          - "tips convert": cli/convert.md
          - "tips subsample": cli/subsample.md
          - "tips wizard": cli/wizard.md
      - Python API:
          - "tips.io": python/io.md
          - "tips.bias": python/bias.md
          - "tips.subsample": python/subsample.md
          - "tips.reduction": python/reduction.md
  - Develop:
      - Overview: develop.md
      - Writing you own:
          - Format: dev/format.md
          - Dataset: dev/dataset.md
          - Module: dev/module.md
          - Recipie: dev/pattern.md
      - Contributing:
          - Developer setup: dev/setup.md
          - Guideline: dev/guideline.md
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  custom_dir: docs/overrides
  palette:
    primary: teal
    accent: teal
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
plugins:
  - search
  - mike
  - bibtex:
      bib_file: "docs/references.bib"
      cite_style: "pandoc"
extra:
  version:
    provider: mike
markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/extra.css
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
