site_name: PiNN<span>AcLe</span>
repo_name: teoroo-cmc/pinnacle
repo_url: https://github.com/teoroo-cmc/pinnacle/
site_url: https://teoroo-cmc.github.io/pinnacle/

nav:
  - Home: index.md
  - Tutorial:
    - First project: tutorial/first_project.md
    - Configure: tutorial/configure.md
  - Modules:
    - ASE: module/ase.md
    - CP2K: module/cp2k.md
    - LAMMPS: module/lammps.md
    - PiNN: module/pinn.md
    - Utils: module/utils.md
  - Profiles:
    - Overview: profiles/overview.md
    - Alvis: profiles/alvis.md
    - Teoroo2: profiles/teoroo2.md

theme:
  name: flux

plugins :
  - search
  - bibtex:
      bib_file: "docs/references.bib"

markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
  - toc:
      toc_depth: 3

extra_javascript:
  - js/mathjax.js
