site_name: PiNN<span>AcLe</span>
repo_name: teoroo-cmc/pinnacle
repo_url: https://github.com/teoroo-cmc/pinnacle/
site_url: https://teoroo-cmc.github.io/pinnacle/

nav:
  - Home: index.md
  - Tutorial:
    - Get started: tutorial/get_started.md
    - Workflow: tutorial/workflow.md
    - Configure: tutorial/configure.md
  - Manual:
    - Overview: manual.md
    - Recipes:
      - AcLe: recipe/acle.md
    - Modules:
      - TIPS: module/tips.md
      - PiNN: module/pinn.md
      - CP2K: module/cp2k.md
      - ASE: module/ase.md
      - DFTB+: module/dftb.md
      - molutils: module/molutils.md
      - LAMMPS: module/lammps.md
  - Profiles:
    - Overview: profiles/overview.md
    - Alvis: profiles/alvis.md
    - Teoroo2: profiles/teoroo2.md

theme:
  name: flux

plugins :
  - search
  - bibtex:
      bib_file: "docs/references.bib"

markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
  - toc:
      toc_depth: 3

extra_javascript:
  - js/mathjax.js
