name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: yqshao/mkdocs-material@y7.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
